# Generated by Django 4.2.1 on 2023-06-09 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_view', '0002_alter_person_options_alter_person_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID único para la entidad Grupo', primary_key=True, serialize=False),
        ),
    ]
