# Generated by Django 4.2.1 on 2023-06-09 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_view', '0004_alter_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID único para la entidad Person', primary_key=True, serialize=False),
        ),
    ]
